# Generated by Django 5.0.4 on 2024-05-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
    ]
