# Generated by Django 5.0.4 on 2024-05-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ('name',), 'verbose_name': 'industry', 'verbose_name_plural': 'industries'},
        ),
    ]
